### ISSUE TITLE
First bin of non-negative variable starts below zero

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#19]
In the query below, it seems all values of the variable are positive (it's a "hospitalization cost" so can't be negative), but the first bin in the example below is [-81.8, 81.8].  Should the first binStart be zero?

https://localhost:3000/eda-subsetting-service/apps/pass/visualizations/numeric-histogram-bin-width
```
#POST data
{"studyId":"GEMSCC0002-1","filters":[],"config":{"outputEntityId":"EUPATH_0000738","valueSpec":"count","xAxisVariable":{"entityId":"EUPATH_0000738","variableId":"EUPATH_0010266"}}}
```
the relevant part of the response:
```
{
	"binStart": [
		"-81.8",
		"1.39e+03",
		"1.88e+03",
		"245",
		"3.52e+03",
		"409",
		"573",
		"736",
		"81.8",
		"900"
	]
}
{
	"summary": {
		"min": 0,
		"q1": 0,
		"median": 0,
		"mean": 97.5077,
		"q3": 25,
		"max": 3600
	}
}
```

**Comment by d-callan** [comment]
fixed in plot.data v0.4.3

**Comment by bobular** [comment]
Hi @d-callan  - I still see the negative bin starts.  Has this been rolled out to https://feature.clinepidb.org/eda-data ?

**Comment by d-callan** [comment]
found a bug in a function i was borrowing from ggplot2 for binning. stopped using their version now, and will have to maintain our own i suppose. fixed in plot.data v0.5.1

**Comment by bobular** [comment]
Hi @d-callan - confirming this is now fixed on the service running at https://feature.clinepidb.org/eda-data - thank you!
